""" add_more_tables

Revision ID: 63a30ef089e9
Revises: 76d9b36c70ef
Create Date: 2024-12-18 09:32:24.039835

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '63a30ef089e9'
down_revision = '76d9b36c70ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('type_payment_id', sa.Integer(), nullable=False),
    sa.Column('name_payment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_payment_id'),
    schema='my_app_schema'
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('service_id'),
    schema='my_app_schema'
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['my_app_schema.clients.client_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['my_app_schema.hotels.hotel_id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['my_app_schema.room_types.room_type_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    schema='my_app_schema'
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['my_app_schema.hotels.hotel_id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['my_app_schema.room_types.room_type_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    schema='my_app_schema'
    )
    op.create_table('stays',
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('type_payment_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['my_app_schema.bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['my_app_schema.rooms.room_id'], ),
    sa.ForeignKeyConstraint(['type_payment_id'], ['my_app_schema.payment_types.type_payment_id'], ),
    sa.PrimaryKeyConstraint('stay_id'),
    schema='my_app_schema'
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['my_app_schema.hotels.hotel_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['my_app_schema.stays.stay_id'], ),
    sa.PrimaryKeyConstraint('feedback_id'),
    schema='my_app_schema'
    )
    op.create_table('service_usage',
    sa.Column('service_usage_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['my_app_schema.services.service_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['my_app_schema.stays.stay_id'], ),
    sa.PrimaryKeyConstraint('service_usage_id'),
    schema='my_app_schema'
    )
    op.alter_column('room_types', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='my_app_schema')
    op.alter_column('room_types', 'room_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='my_app_schema')
    op.alter_column('room_types', 'price_per_night',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='my_app_schema')
    op.alter_column('room_types', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='my_app_schema')
    op.drop_constraint('room_types_hotel_id_fkey', 'room_types', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key(None, 'room_types', 'hotels', ['hotel_id'], ['hotel_id'], source_schema='my_app_schema', referent_schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_types', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key('room_types_hotel_id_fkey', 'room_types', 'hotels', ['hotel_id'], ['hotel_id'], source_schema='my_app_schema', referent_schema='my_app_schema', ondelete='CASCADE')
    op.alter_column('room_types', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='my_app_schema')
    op.alter_column('room_types', 'price_per_night',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='my_app_schema')
    op.alter_column('room_types', 'room_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='my_app_schema')
    op.alter_column('room_types', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='my_app_schema')
    op.drop_table('service_usage', schema='my_app_schema')
    op.drop_table('feedback', schema='my_app_schema')
    op.drop_table('stays', schema='my_app_schema')
    op.drop_table('rooms', schema='my_app_schema')
    op.drop_table('bookings', schema='my_app_schema')
    op.drop_table('services', schema='my_app_schema')
    op.drop_table('payment_types', schema='my_app_schema')
    # ### end Alembic commands ###
