""" add_roomtype_table

Revision ID: 76d9b36c70ef
Revises: 7fb9eb55ab4d
Create Date: 2024-12-18 08:43:38.790850

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '76d9b36c70ef'
down_revision = '7fb9eb55ab4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_types',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['my_app_schema.hotels.hotel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_type_id'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_types', schema='my_app_schema')
    # ### end Alembic commands ###
